package utils.context;

public enum ContextKeys {
        BASEURI,PNRCODE,BUSPARTNER,
        EMAIL,PASS,
        FLIGHTNUMBER1,FLIGHTNUMBER2,FLIGTNUMBERPAYMENT1,FLIGTNUMBERPAYMENT2
        ,WHERETO,WHEREFROM,
        SELECTEDTRIPTIME,SELECTEDTRIPPRICE,
        SELECTEDSEA,SEATCOUNT,SEASEATNUMB,SEASEATCODE,HOTELLOCATION


}
